services:
  broker-service:
    build:
      context: broker-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
  auth-service:
    build:
      context: auth-service
      dockerfile: